### ISSUE TITLE
Colorize "changes to be commited"

### ISSUE THREAD

**Issue by rugk** [indie-mirror/gnomit#1]
It would be great to have these colored in a way the usual status messages with `$ git status` are colored (if you have some good zsh plugins or so).

So orange for "modified", red for "removed" and green for "added". 

The use case is just that I can have an overview of what I am committing just to verify it again (I often just automatically do `git add .&& git commit -a` so I do not check-in manually) and re-check that I am not doing bad stuff. :wink: 
I guess this use case is what git devs had in mind when adding this to commit messages, so you may just colorize it, so I see it better (the grey is really light) and it strikes me if I am about to commit a wrong file. 

Pay attention to the fact that the text is localized in different languages in git.

**Comment by aral** [comment]
Thank you for the suggestion.

I don’t currently have plans to parse the commit message since (as you mention at the end of your issue), the text is localised. Parsing it for semantics is thus not a trivial matter and not the approach that should be taken if we want to add semantics to the tools (I captured a similar approach in [issue 5 on the main repository](https://source.ind.ie/gnome/gnomit/gjs/issues/5) but I’m going to close that for the same reason.)

If we do want to explore adding semantics to the tool at some point, we should use the git tool itself to gather data about the commit and present it optimally. See [issue #14 in the main repository](https://source.ind.ie/gnome/gnomit/gjs/issues/14).
